---
title: "About"
---

Hello,
 
 Am Forgive Agbesi, but prefare to be called Akosua
 
 I am a diligent, resourceful and enthusiastic person
 I have extensive experience in ERP Systems with a strong background in software development
 I have the passion for creating efficient, scalable, and maintainable applications. 
 Proficient in X++, C# and the.NET framework, 
 with expertise in designing and implementing complex software solutions. 
 I Adept at collaborating with cross-functional teams to analyze requirements, architect solutions, and deliver high-quality software on time.
 Experienced in various software development methodologies, including Agile and Scrum.

 I am continuously staying updated with the latest industry trends and technologies to ensure the development of cutting-edge solutions.
 Strong problem-solving skills and a commitment to writing clean, well-documented code.

 I have a BSC in Information Technology from the university of Ghana,
 Currently, am persuing my masters in the University of British Columbia, Master of Data Science.

 I love reading comics and not forgetting choral music.

 Join me as i exploy how to merge the powers of Enterprise Resource Planning (ERP) tools with data science for better business processes.
  

